[project]
name = "graphsynth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pygame>=2.6.1",
    "sounddevice>=0.5.5",
]
